### ISSUE TITLE
Does this work on a real Mac with OpenCore?

### ISSUE THREAD

**Issue by Piipperi** [aluveitie/RadeonSensor#8]
Hi,

I use OpenCore on my MacBook Pro to get external GPU support for my RX 5700 XT. The package I use includes Lilu, does this mean that the RadeonSensor.kext should work with my config? And if I've understood correctly, do I need to use the SMCRadeonGPU.kext for iStats support (I don't have VirtualSMC, but I guess I can implement it to my config if required)?

Thanks.

**Comment by aluveitie** [comment]
I guess it should work at least with the RadeonGadget.

If it works out with iStats I don't know. iStats only shows keys that are specified for a particular SMBIOS, if the MacBook Pro SMBIOS you're using doesn't have the keys iStats won't show it.
Since most people use it on hackintoshes I've chosen what makes sense for MacPro7,1 and such.

**Comment by Piipperi** [comment]
Thanks for the info, I will test it out later today how it works out.
